name : Build App

on:
    push:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: build-push
          uses: docker/build-push-action@v1
          with:
            username: ${{ secKrets.DOCER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            registry: docker.io
            repository: gabrield0cker/cd
            tag_with_sha: true
    sonarcloud:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
          with:
            # Disabling shallow clone is recommended for improving relevancy of reportingws
            fetch-depth: 0
        - name: SonarCloud Scan
          uses: sonarsource/sonarcloud-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: "${{ secrets.SONAR_TOKEN }}"
    Owasp:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Install NPM dependencies
          run: |
            npm install --production --unsafe-perm

        - name: Upload Artifact
          uses: actions/upload-artifact@v2
          with:
            name: owasp-report
            path: path/to/your/artifact

            