name: Build and Analyze

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Push Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io
          repository: gabrield0cker/cd
          tag_with_sha: true

  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@1.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  OWASP:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install NPM dependencies
        run: |
          npm install

      - name: Run OWASP Dependency Check
        uses: sburris/dependency-check-action@master
        with:
          Project-Name: TestApp

      - name: Archive dependency check reports
        uses: actions/upload-artifact@v1
        with:
          name: reports
          path: reports
